# -*- coding: utf-8 -*-
"""minGPT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihhE2F0GpXaNyrp_USZEsKlG0uo3Wy_U
"""
import torch
from torch.nn import functional as F
import torch.nn as nn



batch_size = 32
block_size = 8
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 32
#-------------------------------------


torch.manual_seed(1337)


#!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

print("length of dataset in characters: ", len(text))

# let's look at the first 1000 characters
print(text[:1000])

#keep track of all unique characters
#gets a sorted list of all the unique characters in the text
chars = sorted(list(set(text)))
#possible elements of our sequences
vocab_size = len(chars)
print(' '.join(chars))
print(vocab_size)

"""We need to tokenize the text. Tokenizing text means to convert raw text as a string to some sequence of integers according to some vocabulary of possible elements.

We are going to build the encoder and the decoder.
"""

#create a mapping from chars to integers
stoi = {ch:i for i,ch in enumerate(chars) }
itos = {i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] #take a string, output list of integers
decode = lambda l: ''.join([itos[i] for i in l]) #take list of integers, output string

print(encode("hii there"))

"""Google uses SentencePiece, which encodes strings and text into integers. Read more on later. OpenAI uses tiktoken."""

#we can load in the entire text dataset and then load it into a tensor
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

"""We are never going to feed all the data to the transformer all at once. We sample random chunks of the dataset and train with chunks at a time. Each chunk has a blocksize (maximum length of chunk/set etc)."""

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y = x.to(device), y.to(device)
    return x,y


@torch.no_grad()
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train', 'val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, Y = get_batch(split)
      logits, loss = model(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out

class BigramLanguageModel(nn.Module):

  def __init__(self):
    super().__init__()
    #each token directly reads off the logits for the next token from a lookup table
    self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
    self.lm_head = nn.Linear(n_embd, vocab_size)

  def forward(self, idx, targets=None):
    #idx and targets are both (B,T) tensor of integers
    tok_emb = self.token_embedding_table(idx) #(B,T,C)
    logits = self.lm_head(tok_emb) #(B,T,vocab_size)

    if targets is None:
      loss = None
    else:
      B,T,C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self(idx)
      logits = logits[:,-1,:]
      probs = F.softmax(logits, dim =-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx,idx_next), dim = 1)
    return idx
  
  

model = BigramLanguageModel()
m = model.to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)

for iter in range(max_iters):
  
  if iter % eval_interval == 0:
    losses = estimate_loss()
    print(f"step{iter}, trainloss{losses['train']:.4f}, val loss{losses['val']:.4f}")

  xb, yb = get_batch('train')

  logits, loss = model(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

context = torch.zeros((1,1), dtype = torch.long, device=device)

#38.36 in Video
